export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";

export const FETCHING_DATA_DETAIL = "FETCHING_DATA_DETAIL";
export const FETCHING_DATA_DETAIL_SUCCESS = "FETCHING_DATA_DETAIL_SUCCESS";
export const FETCHING_DATA_DETAIL_FAILURE = "FETCHING_DATA_DETAIL_FAILURE";
